name: GithubActionPushDemo Branches

on: 
 push: 
  branches: 
   - main
   - develop

jobs:
  hello:
    runs-on: ubuntu-22.04

    steps:
      - name: Hello step
        run: |
          echo "hello world demo branch"
          echo "hello world 2 demo branch"
  
